### ISSUE TITLE
Error with gulp start

### ISSUE THREAD

**Issue by jchomarat** [mmick66/electrate#10]
Hello,

Great starting project- I also did not want to have a web server running ...
I just found a small issue when executing npm start
The window opens, but an error occurs on closing the window

[15:16:34] The following tasks did not complete: start, <anonymous>

This can be solved by setting the callback function async on your gulpfile.js, line 48

gulp.task('start', gulp.series('copy', 'build', **async** () => {
    spawn(cmd('electron'), args(), { stdio: 'inherit', cwd: '.', shell: true }).on('close', exit);
}));

Julien

**Comment by mmick66** [comment]
I have changed a few things on the project and I am no longer receiving the error.

**Comment by ZeCarlosCoutinho** [comment]
Was this solved? I am still having problems with the npm start.

> [23:55:41] Starting '<anonymous>'...
> [23:55:41] '<anonymous>' errored after 11 ms
> [23:55:41] Error: spawn node_modules/.bin/electron ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
>     at onErrorNT (internal/child_process.js:431:16)
>     at processTicksAndRejections (internal/process/task_queues.js:81:17)
> [23:55:41] 'start' errored after 1.28 s
> [23:55:41] 'default' errored after 1.29 s
> [23:55:41] The following tasks did not complete: watch
> [23:55:41] Did you forget to signal async completion?
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! electrate@1.0.0 start: `gulp`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electrate@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>

**Comment by mmick66** [comment]
I cannot reproduce. Please tell me your system's specs.

**Comment by ZeCarlosCoutinho** [comment]
Using Windows 10,
npm version: 6.9.0 
gulp version: 4.0.2
electron version: 5.0.9

What other specs do you need?

**Comment by mmick66** [comment]
It's fine. I will check it out later today... Thanks!

**Comment by ricardomansano** [comment]
In time...
It work's on Linux/Win as well

const exec = require('child_process').exec;
..
gulp.task('start', gulp.series('build', () => {
    return exec(
        __dirname+'/node_modules/.bin/electron . '
    ).on('close', () => process.exit());

**Comment by mmick66** [comment]
@ricardomansano Thank you so much... It's often hard to find the time to work on open source projects like these and support such as yours means a lot! Could any of you please add a pull request? Thanks again!
