### ISSUE TITLE
Can't run "npm run start"

### ISSUE THREAD

**Issue by ptksp-afan** [mmick66/electrate#6]
When I run `npm run start` after `npm install` there is an error
`Starting '<anonymous>'...
[10:10:56] '<anonymous>' errored after 12 ms
[10:10:56] Error: spawn ./node_modules/.bin/electron ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[10:10:56] 'start' errored after 856 ms`

**Comment by vonBuzzBeurling** [comment]
Same Here, any luck ?

**Comment by mmick66** [comment]
Did you resolve it?

**Comment by mtiziano** [comment]
i have the same error

> [10:04:32] Finished 'build-css' after 34 ms
[10:04:32] Starting 'build-js'...
[10:04:32] Finished 'build-js' after 504 ms
[10:04:32] Finished 'build' after 545 ms
[10:04:32] Starting '<anonymous>'...
[10:04:32] '<anonymous>' errored after 6.49 ms
[10:04:32] Error: spawn ./node_modules/.bin/electron ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[10:04:32] 'start' errored after 663 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electrate@1.0.0 start: `gulp start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electrate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:

**Comment by guibonafini** [comment]
What OS you are using? I had same problem in Windows 10 and i resolved changing the following line a gulpfile.js:

From: 
`const cmd   = (name) => `./node_modules/.bin/${name}`;`
To: 
`const cmd   = (name) => path.join('.', 'node_modules', '.bin', name);`

Additionally, i added the `cwd:'.'` parameter in spawn options under gulp.task

**Comment by mmick66** [comment]
@guibonafini Could you please add a pull request?

**Comment by guibonafini** [comment]
Pull request added
